### ISSUE TITLE
Increase Ward protection

### ISSUE THREAD

**Issue by polaco1782** [nxPublic/ValheimPlus#10]
Hey,

Awesome work! 

We need wards to work correctly for a decent public experience...  I mean, protect from players destroying everything, not only locking doors/chests.

I've been reading code using dnSpy, seems its under Privatearea class

**Comment by b3ck** [comment]
I **_+1_** this and Workbench area increase would be good as well.

**Comment by nxPublic** [comment]
Added in 0.8.5
