### ISSUE TITLE
Hoe & Advanced Building Mode

### ISSUE THREAD

**Issue by Samsterious** [nxPublic/ValheimPlus#14]
The Hoe appears to be stuck in Advanced Building Mode. I'm not entirely sure how this began because I can't remember if I've tried using it since installing this mod. It appears to be in Advanced Building Mode because using the arrow keys slightly moves the target indicator. However, using the hotkey to exit Advanced Building Mode does not solve the issue.

This issue persists across both new and old characters but not across worlds. The item can be handed to friends in multiplayer (who also have the mod) and be used as normal without issue.

We are using version 0.5 of the BepiNex + ValheimPlus package.

**Comment by nxPublic** [comment]
I am aware of this issue and it has been fixed for 0.6

**Comment by infekSK** [comment]
I was having the same issue but then it started working again. Strange.

**Comment by nxPublic** [comment]
Fixed in 0.6
