### ISSUE TITLE
Bug with farming&advanced building

### ISSUE THREAD

**Issue by Jeffrey2457** [nxPublic/ValheimPlus#18]
When advanced building mode is enabled in the config, I cannot plant any seeds. I can build just fine with it, just not farming. It 'drops' the 'ghost' at your feet, as if you were still deciding where to place the seed, but you cannot mouse-click to actually place it, nor can you even move the 'ghost' around, though arrow keys does work for moving.

**Comment by nxPublic** [comment]
Issue is resolved in 0.6
