### ISSUE TITLE
Items Weight

### ISSUE THREAD

**Issue by AissuLegris** [nxPublic/ValheimPlus#19]
Hello,

Thanks for your fabulous mod.

I noticed that the weight of the objects was not reduced,  changing the parameters (0.5, 0.8), with the lines set to "TRUE".

[This is my parameters]

[Items]
enabled=true
; enable/disable Building changes

noTeleportPrevention=true
; default is false (boolean)

baseItemWeightReduction=0.7
;(float), removes from value (original - (original * baseItemWeightReduction). 
; 1 is 100% weight reduction of every item, 0.5 is 50%.

Thank you, and bring you back the problems if I come across to help you!

**Comment by nxPublic** [comment]
You are not running the latest version 0.6

```ini
baseItemWeight=0
; default is 0, this is a percent value. (default - foodDurationMultiplier%)
; 10 is 10% weight reduction of every item, 50 is 50%, -50% is +50% weight.
; if you set this to a -number, the base weight will be increased by that much in %
```
