### ISSUE TITLE
Simple stupid question

### ISSUE THREAD

**Issue by AissuLegris** [nxPublic/ValheimPlus#20]
Hello again,

Silly question, but how do you update the mod with your latest changes? (The 0.5 file on your download link is different from the one offered for download by GitHub)

Thank you !

**Comment by nxPublic** [comment]
Download Page provides instructions.

**Comment by AissuLegris** [comment]
Hi,

Thanks, this link ? (In the main page) https://mega.nz/file/0UAlxQwK#47InGOb8ViI6GyBDArpbhkbMTBklXdyRSmAc4-BZpJY

**Comment by nxPublic** [comment]
https://github.com/nxPublic/ValheimPlus/releases/download/0.6/Valheim_Bepinex_5.4.5+ValheimPlus-0.6.zip
