### ISSUE TITLE
Mod disables Steam Overlay (+Steam functions like Screenshot)

### ISSUE THREAD

**Issue by infernalshade** [nxPublic/ValheimPlus#23]
Just found out the Mod disables the default Steam Screenshot Feature (F12), maybe it overwrites the F12 Button, is there a way to fix this?

EDIT: It not only disables the Screenshot feature, but the whole Steam Overlay.

**Comment by nxPublic** [comment]
This is not caused by my modification.

I am unable to reproduce your issue.
