### ISSUE TITLE
Feature Request. Extended Plot/Build Area

### ISSUE THREAD

**Issue by DaNnySaNn8391** [nxPublic/ValheimPlus#24]
I'm not sure if you're already working on this or not, but I think it would be really cool if you found a way to either increase or remove the building limit around stonemasons/workbenches to allow us to build without having to constantly place workbenches/stonemasons around. Not a big deal just a small thought.

**Comment by nxPublic** [comment]
Implemented in 0.8.5, credits to @Drakeny
