### ISSUE TITLE
[Feature Request] Notification on gained XP

### ISSUE THREAD

**Issue by matias-kovero** [nxPublic/ValheimPlus#29]
Not sure how much there is control to the UI, however making skill grinding more rewarding and active would be a nice add-on.

**When player does something to acclaim more xp to a specific skill, the game would prompt it in the bottom-right corner.**
Format would be: <Skill_name> (<amount_gained>)

Ex. Cutting wood, it would prompt: 
**Woodcutting (+5)**

_*and maybe add to total amount as well after it? ex. Woodcutting (+5) 255/600_

I'm no UI specialist, but suggestion to have it as an list. 
Every new text would be added to the bottom of the list + lines would fade after x seconds.

`Woodcutting (+5)`
`Woodcutting (+5)`
`Sword (+2)`

_Thanks_

**Comment by nxPublic** [comment]
This is a great idea, i will certainly put that high on the list of things to do!

**Comment by nxPublic** [comment]
Its in 0.8
