### ISSUE TITLE
Potential known issue with maximum players modification of the server.

### ISSUE THREAD

**Issue by nxPublic** [nxPublic/ValheimPlus#3]
I am at this point in time not able to test the 10 players cap properly since I do not have 10 people to help me with that.

My current expectation is that the client actually prevents you from joining servers with more than 10 people max since it does not actually load the maximum amount of players from the server but just uses a hardcoded value. In case that is the case, I will have to make some small adjustments but it should be fixed fairly easy.

**Comment by nxPublic** [comment]
![image](https://user-images.githubusercontent.com/39051287/107923965-14e6a680-6f27-11eb-8503-61700f89de8a.png)

**Comment by bshenk** [comment]
Is this confirmed to be working?
