### ISSUE TITLE
[Feature Request] Add support for Linux dedicated servers

### ISSUE THREAD

**Issue by rosudrag** [nxPublic/ValheimPlus#30]
ValheimPlus seems to work fine on Windows servers but not on unix hence it won't work on servers booted up via docker.

Edit: reading about HarmonyX made me think that this is probably wrong end of the stick to put the feature request in. The dockerfile is probably the place where it might need to happen...

**Comment by rosudrag** [comment]
This was as simple as adding these env variables:
      - DOORSTOP_ENABLE=TRUE
      - DOORSTOP_INVOKE_DLL_PATH=/home/steam/valheim/BepInEx/core/BepInEx.Preloader.dll
      - LD_LIBRARY_PATH=/home/steam/valheim/doorstop_libs
      - LD_PRELOAD=libdoorstop_x64.so
      - DYLD_LIBRARY_PATH=/home/steam/valheim/doorstop_libs
      - DYLD_INSERT_LIBRARIES=/home/steam/valheim/doorstop_libs/libdoorstop_x64.so

**Comment by zedle** [comment]
@rosudrag Did you have to compile the mod yourself? I grabbed doorstop and modified the bash to export those vars but get a bunch of errors on start.

`Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/BepInEx.Preloader.dll.so
Got image: 0x55dae2927240
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/BepInEx.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/System.Core.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/MonoMod.Utils.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/Mono.Cecil.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/Mono.Cecil.Mdb.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/Mono.Cecil.Pdb.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/Mono.Cecil.Rocks.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/System.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/0Harmony.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/MonoMod.RuntimeDetour.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/Mono.Security.dll.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/data-0x55dae2e83a90.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/`D▒▒▒U/mono/aot-cache/amd64/data-0x55dae2e83a90.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/dl
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/dl
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl.so
Fallback handler could not load library /home/steam/Valheim/valheim_server_Data/Mono/libdl
`

**Comment by rosudrag** [comment]
@zedle I've actually failed to get it working ... you can check the ticket on the docker build I'm trying to get this working https://github.com/mbround18/valheim-docker/issues/130

**Comment by zedle** [comment]
@rosudrag got discord? i got it loading pretty far, it just gives me these now:

`[Error  : Unity Log] MethodAccessException: Method 'Console.AddString(string)' is inaccessible from method 'ValheimPlus.VersionInfo+HookConsole.Postfix(Console&)'`
