### ISSUE TITLE
BepInEx console?

### ISSUE THREAD

**Issue by KeananFlowerday** [nxPublic/ValheimPlus#34]
can we work on not opening console every time we run the game? kinda annoying ngl

![image_2021-02-18_112031](https://user-images.githubusercontent.com/25819075/108335131-50110000-71db-11eb-91e0-28a13e517cb2.png)

**Comment by nxPublic** [comment]
You can modify this yourself.

Valheim\BepInEx\config\BepInEx.cfg
```ini
[Logging.Console]
## Enables showing a console for log output.
# Setting type: Boolean
# Default value: false
Enabled = false
```

After version 1.0, the console will be inactive by default.
