### ISSUE TITLE
Shared Map

### ISSUE THREAD

**Issue by TapyCz** [nxPublic/ValheimPlus#40]
What happens when I'm offline and a friend discovers another part of the map? Can't I see it? Is it not possible to make the map completely shared and, for example, the markers on it to?

Thanks, amazing job!

**Comment by nxPublic** [comment]
We are working on a shared map system using the networking aspect of the game. Currently you only get map exploration when you are online and your friend is online with enabled map sharing.

This will take time.

More news on that soon.
