### ISSUE TITLE
Disable damage to buildings.

### ISSUE THREAD

**Issue by AkiNaruse** [nxPublic/ValheimPlus#42]
In version 0.6, damage to buildings was disabled.
In version 0.8, it seems that building damage is enabled.
Is it possible to add a parameter to disable it?

**Comment by nxPublic** [comment]
Yes. It will be back in the next update.

**Comment by AkiNaruse** [comment]
cool!

**Comment by nxPublic** [comment]
```ini
[Building]
disableStructualIntegrity=false
```
in 0.8.5
