### ISSUE TITLE
Advanced Building/Editing Mode Rotation Speed: Notification Delay Causes Confusion

### ISSUE THREAD

**Issue by Samsterious** [nxPublic/ValheimPlus#46]
**Version:** ValheimPlus v0.8

When adjusting the rotation speed, the message that appears to show its new value takes quite a long time to fade and be replaced by the next queued message. Especially when fine-tuning, this can cause confusion as to what the current value actually is if the user has not correctly memorized and counted their keypresses. 

I believe a clearer implementation would involve instantly quelling the current message and replacing it with a new notification that shows the updated value in real time.

The type of notification in question:
![image](https://user-images.githubusercontent.com/20689511/108582554-f5fe6080-72e8-11eb-8899-92f380f27ab9.png)

**Comment by nxPublic** [comment]
Due to the fact that we have not yet implemented additional UI elements, which we are working on, this is the best we can do at the moment. You can check the actual speed changes also in the BepInEx console in real time.

We will improve it in the future as soon as we have GUI stuff in place.
