### ISSUE TITLE
[feature] Do not replace config on updates / place config elsewhere

### ISSUE THREAD

**Issue by LordMike** [nxPublic/ValheimPlus#52]
Would it be possible to avoid replacing the config with a new one on updates?

I'm thinking it should be possible to:

* Not ship the config, but create it on first run
  * Ship a `valheim_plus.cfg.example`, that users can copy if they want to change the config _before_ they start the game
  * On updates w/ new config options that aren't defined in the file - you could rewrite it with the config that is set, and the new values (with defaults)
* Like above, but place the config outside the game folder - like with the save games at `%HOMEPATH%\AppData\LocalLow\IronGate\Valheim`

**Comment by nxPublic** [comment]
Today i merged a pull request with a entirely new config system.

In the future, v+ will automatically add not set config parameters to your configuration file on start up with default values.

No ETA on that systems improvement to do it but it has a high priority.

About the location of the config file, given the way this mod works and how its installed this is at the moment the best way to supply it. It would also be fairly weird at a later stage to have the config of all other mods in the same location, just v+ not.
