### ISSUE TITLE
[feature] modification of m_dataPerSec in Server section

### ISSUE THREAD

**Issue by lloesche** [nxPublic/ValheimPlus#58]
We just had a discussion in https://github.com/lloesche/valheim-server-docker/discussions/58 about the inclusion of `m_dataPerSec` in the Server section of V+.
Right now we're running recompiled `assembly_valheim.dll` to increase outbound send rate to e.g. 500kb/s (default is ~64kb/s). Would be neat if V+ just had config file support for it.

On busy servers with the necessary bandwidth it makes a huge difference. We have 8-10 people playing simultaneously with lots of wolfs running around. Before the patch wolfs would mostly just teleport esp. during attack waves. Now everything is buttery smooth.

**Comment by nxPublic** [comment]
This will be included in version 0.8.5
