### ISSUE TITLE
Disable Password Server Start  Up Loop

### ISSUE THREAD

**Issue by calebwarta** [nxPublic/ValheimPlus#61]
Maybe I'm doing this wrong but I have had no luck using the disable password feature in the Mod config tried also disabling it in the game files and it causes the server to restart in my Unraid docker every few minutes.

I have not tried disabling the public server option in the game settings as I feel that would be pointless because you could do this without the password removal from the mod

**Comment by astranberg** [comment]
You have to delete the **-password "pass"** from start_headless_server.bat.
