### ISSUE TITLE
[Feature Request] Increase Server Data Send/Receive Cap

### ISSUE THREAD

**Issue by astranberg** [nxPublic/ValheimPlus#62]
Requesting ability to increase m_datapersec found in assembly_valheim.dll.
If done in the server, increases the maximum datareceived (default ~64 kb/s).
If done in the client, increases the maximum datasent (default ~64 kb/s).
This can reduce or even eliminate lag for some. Would be nice to do it with V+. It's a pain to teach each person joining my server how to edit their dll.

**Comment by Neoony** [comment]
already answered here https://github.com/nxPublic/ValheimPlus/issues/58

**Comment by nxPublic** [comment]
> already answered here #58
