### ISSUE TITLE
Add development setup to the readme

### ISSUE THREAD

**Issue by avivbiton** [nxPublic/ValheimPlus#7]
I think it will allow more programmers to contribute and expend the mod if you add some sort of instructions to the readme on how to setup a development env

**Comment by nxPublic** [comment]
I appreciate the feedback, how ever that's literally already in there at the bottom of the README.md

> # Valheim Plus Compiler Requirements

> You will be dependent on a package of stripped .net/mono Unity files from the Valheim directory.
How to get BepInEx working:

> 1. Download this package:

> https://mega.nz/file/0UAlxQwK#47InGOb8ViI6GyBDArpbhkbMTBklXdyRSmAc4-BZpJY

> 2. Unpack into your Valheim root folder and overwrite every file when asked.

> 3. Add all dll's of "\Valheim\valheim_Data\Managed" folder as references to the project.

> (Except : "mscorlib.dll", "System.Configuration.dll", "System.Core.dll", "System.dll", "System.Xml.dll")

> 4. Add all BepInEx dll's ("Valheim\BepInEx\core") as refernces to the project.

> (Except : "0Harmony.dll", "0Harmony20.dll")

> 5. Add Ini-parser and HarmonyX via nu-get

**Comment by avivbiton** [comment]
Was hoping for something more about the env itself and not about just compiler but nevermind, it is not critical. This will do for now
