### ISSUE TITLE
I cant uninstall it

### ISSUE THREAD

**Issue by namjay1170** [nxPublic/ValheimPlus#81]
Verify integrity results in the game not launching same with reinstalling, adding the mod back and it works as intended

**Comment by nxPublic** [comment]
Rename "winhttp.dll" to "winhttp.disabled.dll" to deactivate the mod being loaded.

**Comment by namjay1170** [comment]
> 
> 
> Rename "winhttp.dll" to "winhttp.disabled.dll" to deactivate the mod being loaded.

Thank you, I found a method via the discord which is different from this. Can you guys throw it onto the mod page so people don't have to dig for it, I guarantee you will get many more like me if you dont

**Comment by nxPublic** [comment]
I noted to add uninstall instructions.
