### ISSUE TITLE
Readme: Maximum coal value is incorrect

### ISSUE THREAD

**Issue by pekac45** [nxPublic/ValheimPlus#9]
```
maximumCoal=10
; default is 10 (int)
```
it should be 20 as default.

**Comment by pekac45** [comment]
same thing with coal usage.
```
coalUsedPerProduct=4
; default is 4 (int)
```
this should be 2 as per:
Full smelter (20 coal + 10 ore) will create 10 ingots and empties out.

**Comment by nxPublic** [comment]
The default values will be adjusted accordingly for 0.6

**Comment by nxPublic** [comment]
Values adjusted in 0.6
